// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = OpeningTextSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NavbarDocumentDataSlicesSlice = HomeSlice;

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Slice Zone field in *Navbar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavbarDocumentDataSlicesSlice>;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NavbarDocumentData>, "navbar", Lang>;

export type AllDocumentTypes = HomepageDocument | NavbarDocument;

/**
 * Primary content in *Navbar → Primary*
 */
export interface HomeSliceDefaultPrimary {
  /**
   * Heading field in *Navbar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navbar*
 */
type HomeSliceVariation = HomeSliceDefault;

/**
 * Navbar Shared Slice
 *
 * - **API ID**: `home`
 * - **Description**: Home
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSlice = prismic.SharedSlice<"home", HomeSliceVariation>;

/**
 * Primary content in *OpeningText → Primary*
 */
export interface OpeningTextSliceDefaultPrimary {
  /**
   * Opener field in *OpeningText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opening_text.primary.opener
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  opener: prismic.RichTextField;
}

/**
 * Primary content in *OpeningText → Items*
 */
export interface OpeningTextSliceDefaultItem {
  /**
   * Call To Action field in *OpeningText → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: call to action button
   * - **API ID Path**: opening_text.items[].call_to_action
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  call_to_action: prismic.RichTextField;
}

/**
 * Default variation for OpeningText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OpeningTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OpeningTextSliceDefaultPrimary>,
  Simplify<OpeningTextSliceDefaultItem>
>;

/**
 * Slice variation for *OpeningText*
 */
type OpeningTextSliceVariation = OpeningTextSliceDefault;

/**
 * OpeningText Shared Slice
 *
 * - **API ID**: `opening_text`
 * - **Description**: OpeningText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OpeningTextSlice = prismic.SharedSlice<
  "opening_text",
  OpeningTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataSlicesSlice,
      AllDocumentTypes,
      HomeSlice,
      HomeSliceDefaultPrimary,
      HomeSliceVariation,
      HomeSliceDefault,
      OpeningTextSlice,
      OpeningTextSliceDefaultPrimary,
      OpeningTextSliceDefaultItem,
      OpeningTextSliceVariation,
      OpeningTextSliceDefault,
    };
  }
}
