// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  home: () =>
    import(
      /* webpackChunkName: "prismic__slices__home" */ "./Navbar/index.vue"
    ),
  opening_text: () =>
    import(
      /* webpackChunkName: "prismic__slices__opening_text" */ "./OpeningText/index.vue"
    ),
};
