// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  opening_text: () =>
    import(
      /* webpackChunkName: "prismic__slices__opening_text" */ "./ActionButton/index.vue"
    ),
};
